# Site configuration
title: "osbuild"
name: "OSBuild"
description: "Build-Pipelines for Operating System Artifacts"
author: "OSBuild Developers"

# Resource configuration
avatar: "images/osbuild.png"
favicon: "images/osbuild.ico"
url: "https://www.osbuild.org"

# Media handles used to autogenerate external links
media:
  github: "osbuild"

# Define collections of sub-pages
collections:
  news:
    output: true
  manpages:
    output: true

# Define default layouts for each page type
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_collections/_manpages"
    values:
      layout: "page"
      permalink: "/man/:title"
  - scope:
      path: "_collections/_news"
    values:
      layout: "news"

# Keep all collections together to avoid naming conflicts
collections_dir: "_collections"

#
# External plugins:
#  - jekyll-sitemap: This creates a sitemap.xml for us, allowing easier
#                    indexing of the entire website.
#
plugins:
  - jekyll-sitemap
